# Generated by Django 3.2.16 on 2022-10-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(height_field='height', upload_to='images/', width_field='width'),
        ),
    ]
