# Generated by Django 3.2.16 on 2022-10-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='dominant_color',
            new_name='color',
        ),
    ]
