version: "3.9"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=images_project
      - POSTGRES_USER=images_user
      - POSTGRES_PASSWORD=images_user_pass
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./media:/var/www/friendlysolutionstest/media
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=images_project
      - POSTGRES_USER=images_user
      - POSTGRES_PASSWORD=images_user_pass
    depends_on:
      - db
volumes:
    pgdata: